name: Controll flow execution

on:
    push: 
    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: building application
              if: github.action_ref == 'ref/hands/main'
              run: echo "Build state where developers works."
    test:
        runs-on: ubuntu-latest
        needs: build
        if: success()
        steps:
            - name: testing application
              run: echo "testers test the application"
    prod:
        runs-on: ubuntu-latest
        needs: test
        if: failure()
        steps: 
            - name: live traffic for users
              run: echo "live traffic for customers"

    pre-prod:
        runs-on: ubuntu-latest
        env:
            RUN.step: 'true'
        steps:
            - name: testing env condition
              if: env.RUN.step == 'true'
              run: execute for RUN env step
              
            