name: Controll flow execution

on:
    push: 
    workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: building application
              run: echo "Build state where developers works."
    test:
        runs-on: ubuntu-latest
        needs: build
        if: success()
        steps:
            - name: testing application
              run: echo "testers test the application"
    prod:
        runs-on: ubuntu-latest
        needs: test
        if: success()
        steps: 
            - name: live traffic for users
              run: echo "live traffic for customers"