10-Execution-flow
on:
    push:
    workflow_dispatch:
        inputs:
            lint-unit-test:
                
    
jobs:
    lint-build:
        runs-on: linux-latest
        steps:
            - name: Building the code 
              run: echo "running the code to make artifacts"
    lint-unit-test:
        runs-on: linux-latest
        steps:
            - name: Running Unit Tests
              needs: lint-build
              run: echo " Executing Unit tests"
    e2e-pre-prod:
        runs-on: linux-latest
        steps:
            - name: Running on pre-prod
              needs: lint-unit-test
              run: echo "If pre-prod success then move to PROD" 
            
            
              

