name: 10-Execution-flow
on:

    push:
    workflow_dispatch:
        
                
    
jobs:
    lint-build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Building the code 
              run: echo "running the code to make artifacts"
    lint-unit-test:
        runs-on: ubuntu-latest
        needs: lint-build
        steps:
           
            - name: "Running Unit Tests"
              run: |
                echo " Executing Unit tests"
    e2e-pre-prod:
        runs-on: ubuntu-latest
        needs: lint-unit-test
        steps:
            - name: Running on pre-prod
              run: echo "If pre-prod success then move to PROD" 
    prod:
        runs-on: ubuntu-latest
        needs: e2e-pre-prod
        steps:
            - name: deploying in the prod
              run: echo "deploying in the prod"
            
            
              

