name: 11.user inputs in workflow dispatch

on:
    workflow_dispatch: 
        inputs:
            environement:
                description: Choose the env to deploy
                required: false
                options:
                    - dev
                    - uat
                    - prod
                default: non
                type: choice
            secrets:
                description: Secrets for the env
                required: true
                default: aws
            notify:
                description: after deployment send the notification
                default: none
                options:
                  - true
                  - false
                type: choice
                required: true
            target: 
                type: environment
                required: true
                description: in which env we deploy
jobs:
    inputs-job:
        runs-on: ubuntu-latest
        environment: ${{inputs.environement}}
        steps:
        
            - name: Deploying in the env
             
              run: |
                echo "Deploying in ${{github.event.inputs.environement}}"
                echo "deploying in env only inputs.env, not adding github and events: ${{inputs.environement}}"
                    
            - name: Using secrets
              run: echo "secrets are ${{inputs.secrets}}"
            - name: Deploying in the Dev env
              if: ${{github.event.inputs.environement == 'dev'}}
              run: echo " Application running in the dev env"
            - name: Deploying in the UAT
              if: ${{github.event.inputs.environement == 'uat'}}
              run: echo "Source code running on the UAT env"
            - name: Deploying in the prod env
              if: ${{github.event.inputs.environement == 'prod'}}
              run: |
                echo "we are deploying in the application in prod env"
            - name: prod
              if: ${{inputs.environement == 'prod'}}
              run: echo 'only inputs and env, not adding github, events'
            - name: notify
              if: ${{github.event.inputs.notify == 'true'}}
              run: echo "notifing deployment completed "

