name: Secrets Automation to the GSM

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the code from the repository

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # GCP Project ID from GitHub Secrets
          install_components: 'beta'  # Install any additional components you need

      - name: Authenticate to GCP project
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'  # Service account key from GitHub 


      - name: Authenticate with GCP Service Account
        run: |
          gcloud auth activate-service-account --key-file="${{ secrets.GCP_CREDENTIALS }}"
        shell: bash

      - name: Retrieve secret from Google Secret Manager
        id: retrieve_secret
        run: |
          # Retrieve the secret value
          SECRET_VALUE=$(gcloud secrets versions access latest --secret="${{ secrets.secret-auto-123 }}")
          echo "secret_value=$SECRET_VALUE" >> $GITHUB_ENV